use mico_ir::*;
use std::collections::HashMap;

pub fn emit_json_ir(design: &Design) -> String {
    // Dependency-free debug-oriented JSON-ish output. Replace with serde_json later.
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"clock_domains\": [\n");
    for (idx, cd) in design.clock_domains.iter().enumerate() {
        comma(&mut out, idx, design.clock_domains.len());
        out.push_str(&format!(
            "    {{\"name\": \"{}\", \"clock\": \"{}\", \"reset\": \"{}\"}}{}\n",
            cd.name,
            cd.clock,
            cd.reset,
            if idx + 1 == design.clock_domains.len() {
                ""
            } else {
                ","
            }
        ));
    }
    out.push_str("  ],\n");
    out.push_str("  \"modules\": [\n");
    for (idx, m) in design.modules.iter().enumerate() {
        out.push_str(&format!(
            "    {{\"name\": \"{}\", \"domain\": \"{}\", \"extern\": {}}}{}\n",
            m.name,
            m.domain,
            m.is_extern,
            if idx + 1 == design.modules.len() {
                ""
            } else {
                ","
            }
        ));
    }
    out.push_str("  ],\n");
    out.push_str("  \"composes\": [\n");
    for (idx, c) in design.composes.iter().enumerate() {
        out.push_str(&format!(
            "    {{\"name\": \"{}\", \"domain\": \"{}\", \"instances\": {}, \"connections\": {}}}{}\n",
            c.name,
            c.domain,
            c.instances.len(),
            c.connections.len(),
            if idx + 1 == design.composes.len() { "" } else { "," }
        ));
    }
    out.push_str("  ]\n");
    out.push_str("}\n");
    out
}

fn comma(out: &mut String, idx: usize, len: usize) {
    let _ = (out, idx, len);
}

pub fn emit_systemverilog(design: &Design) -> String {
    let modules: HashMap<_, _> = design.modules.iter().map(|m| (m.name.clone(), m)).collect();
    let mut out = String::new();
    out.push_str("// Generated by MICO research scaffold.\n");
    out.push_str("// This emitter is conservative and intended as a starting point.\n\n");

    for compose in &design.composes {
        out.push_str(&format!("module {}(\n", compose.name));
        out.push_str("  input logic clk,\n");
        out.push_str("  input logic rst\n");
        out.push_str(");\n\n");

        out.push_str("  // Instances\n");
        for inst in &compose.instances {
            out.push_str(&format!("  {} {} (\n", inst.module, inst.name));
            out.push_str("    .clk(clk),\n");
            out.push_str("    .rst(rst)\n");
            out.push_str("  );\n\n");
        }

        out.push_str("  // Interface-level connections checked by MICO:\n");
        for conn in &compose.connections {
            match &conn.adapter {
                Some(adapter) => out.push_str(&format!(
                    "  // adapt {} -> {} -> {}\n",
                    conn.from, adapter, conn.to
                )),
                None => out.push_str(&format!("  // connect {} -> {}\n", conn.from, conn.to)),
            }
        }

        out.push_str("\n  // TODO: expand interface fields to primitive wires.\n");
        out.push_str("  // The lowering pass should map each interface field to RTL ports.\n");
        out.push_str("endmodule\n\n");
    }

    if design.composes.is_empty() {
        out.push_str("// No compose blocks found.\n");
    }

    // Touch module map to keep the structure ready for a richer emitter.
    let _ = modules;
    out
}

pub fn emit_sva_skeleton(design: &Design) -> String {
    let mut out = String::new();
    out.push_str("// MICO-generated SVA skeleton.\n");
    for iface in &design.interfaces {
        out.push_str(&format!("// Interface {} @{}\n", iface.name, iface.domain));
        for c in &iface.contracts {
            out.push_str(&format!("// contract {}: {}\n", c.name, c.expr));
        }
    }
    out
}
