`default_nettype none

// Generated by MICO.
// Conservative SystemVerilog wrapper emitted from checked typed IR.

module Top(
  input logic clk,
  input logic rst
);

  // Checked interface connections
  // connect p.tx -> c.rx

  // Interface field wires
  logic [31:0] p_tx__c_rx_payload;
  logic p_tx__c_rx_ready;
  logic p_tx__c_rx_valid;

  // Leaf instances
  Producer p (
    .clk(clk),
    .rst(rst),
    .tx_payload(p_tx__c_rx_payload),
    .tx_valid(p_tx__c_rx_valid),
    .tx_ready(p_tx__c_rx_ready)
  );

  Consumer c (
    .clk(clk),
    .rst(rst),
    .rx_payload(p_tx__c_rx_payload),
    .rx_valid(p_tx__c_rx_valid),
    .rx_ready(p_tx__c_rx_ready)
  );

endmodule

`default_nettype wire
