`default_nettype none

// Generated by MICO.
// Conservative SystemVerilog wrapper emitted from checked typed IR.

module Top(
  input logic clk,
  input logic rst
);

  // Checked interface connections
  // connect p.tx -> f.input
  // connect f.output -> c.rx

  // Interface field wires
  logic [31:0] f_output__c_rx_payload;
  logic f_output__c_rx_ready;
  logic f_output__c_rx_valid;
  logic [31:0] p_tx__f_input_payload;
  logic p_tx__f_input_ready;
  logic p_tx__f_input_valid;

  // Leaf instances
  Producer p (
    .clk(clk),
    .rst(rst),
    .tx_payload(p_tx__f_input_payload),
    .tx_valid(p_tx__f_input_valid),
    .tx_ready(p_tx__f_input_ready)
  );

  Fifo f (
    .clk(clk),
    .rst(rst),
    .input_payload(p_tx__f_input_payload),
    .input_valid(p_tx__f_input_valid),
    .input_ready(p_tx__f_input_ready),
    .output_payload(f_output__c_rx_payload),
    .output_valid(f_output__c_rx_valid),
    .output_ready(f_output__c_rx_ready)
  );

  Consumer c (
    .clk(clk),
    .rst(rst),
    .rx_payload(f_output__c_rx_payload),
    .rx_valid(f_output__c_rx_valid),
    .rx_ready(f_output__c_rx_ready)
  );

endmodule

`default_nettype wire
