`default_nettype none

// Generated by MICO.
// Conservative SystemVerilog wrapper emitted from checked typed IR.

module Top(
  input logic clk,
  input logic rst
);

  // Checked interface connections
  // connect source.tx -> linebuf.input
  // connect linebuf.output -> filter.input
  // connect filter.output -> sink.rx

  // Interface field wires
  logic [31:0] filter_output__sink_rx_payload;
  logic filter_output__sink_rx_ready;
  logic filter_output__sink_rx_valid;
  logic [31:0] linebuf_output__filter_input_payload;
  logic linebuf_output__filter_input_ready;
  logic linebuf_output__filter_input_valid;
  logic [31:0] source_tx__linebuf_input_payload;
  logic source_tx__linebuf_input_ready;
  logic source_tx__linebuf_input_valid;

  // Leaf instances
  CasePixelSource source (
    .clk(clk),
    .rst(rst),
    .tx_payload(source_tx__linebuf_input_payload),
    .tx_valid(source_tx__linebuf_input_valid),
    .tx_ready(source_tx__linebuf_input_ready)
  );

  CaseLineBuffer linebuf (
    .clk(clk),
    .rst(rst),
    .input_payload(source_tx__linebuf_input_payload),
    .input_valid(source_tx__linebuf_input_valid),
    .input_ready(source_tx__linebuf_input_ready),
    .output_payload(linebuf_output__filter_input_payload),
    .output_valid(linebuf_output__filter_input_valid),
    .output_ready(linebuf_output__filter_input_ready)
  );

  CaseThresholdFilter filter (
    .clk(clk),
    .rst(rst),
    .input_payload(linebuf_output__filter_input_payload),
    .input_valid(linebuf_output__filter_input_valid),
    .input_ready(linebuf_output__filter_input_ready),
    .output_payload(filter_output__sink_rx_payload),
    .output_valid(filter_output__sink_rx_valid),
    .output_ready(filter_output__sink_rx_ready)
  );

  CaseFrameSink sink (
    .clk(clk),
    .rst(rst),
    .rx_payload(filter_output__sink_rx_payload),
    .rx_valid(filter_output__sink_rx_valid),
    .rx_ready(filter_output__sink_rx_ready)
  );

endmodule

`default_nettype wire
