`default_nettype none

// Generated by MICO.
// Conservative SystemVerilog wrapper emitted from checked typed IR.

module Top(
  input logic clk,
  input logic rst
);

  // Checked interface connections
  // adapt sensor.tx -> CaseWiden32To64 -> accel.rx
  // connect accel.tx -> host.rx

  // Interface field wires
  logic [63:0] accel_tx__host_rx_payload;
  logic accel_tx__host_rx_ready;
  logic accel_tx__host_rx_valid;
  logic [63:0] casewiden32to64_0__accel_rx_payload;
  logic casewiden32to64_0__accel_rx_ready;
  logic casewiden32to64_0__accel_rx_valid;
  logic [31:0] sensor_tx__casewiden32to64_0_in_payload;
  logic sensor_tx__casewiden32to64_0_in_ready;
  logic sensor_tx__casewiden32to64_0_in_valid;

  // Leaf instances
  CaseSensor32 sensor (
    .clk(clk),
    .rst(rst),
    .tx_payload(sensor_tx__casewiden32to64_0_in_payload),
    .tx_valid(sensor_tx__casewiden32to64_0_in_valid),
    .tx_ready(sensor_tx__casewiden32to64_0_in_ready)
  );

  CaseAccel64 accel (
    .clk(clk),
    .rst(rst),
    .rx_payload(casewiden32to64_0__accel_rx_payload),
    .rx_valid(casewiden32to64_0__accel_rx_valid),
    .rx_ready(casewiden32to64_0__accel_rx_ready),
    .tx_payload(accel_tx__host_rx_payload),
    .tx_valid(accel_tx__host_rx_valid),
    .tx_ready(accel_tx__host_rx_ready)
  );

  CaseHostSink64 host (
    .clk(clk),
    .rst(rst),
    .rx_payload(accel_tx__host_rx_payload),
    .rx_valid(accel_tx__host_rx_valid),
    .rx_ready(accel_tx__host_rx_ready)
  );

  // Explicit adapters
  CaseWiden32To64 casewiden32to64_0 (
    .clk(clk),
    .rst(rst),
    .in_payload(sensor_tx__casewiden32to64_0_in_payload),
    .in_valid(sensor_tx__casewiden32to64_0_in_valid),
    .in_ready(sensor_tx__casewiden32to64_0_in_ready),
    .out_payload(casewiden32to64_0__accel_rx_payload),
    .out_valid(casewiden32to64_0__accel_rx_valid),
    .out_ready(casewiden32to64_0__accel_rx_ready)
  );

endmodule

`default_nettype wire
