#!/usr/bin/env python3
"""Write compact paper tables from frozen MICO evidence artifacts."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import json
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment guidance
    raise SystemExit("PyYAML is required. Run this through scripts/eda-docker.*.") from exc


REPO_ROOT = Path(__file__).resolve().parents[1]


def repo_path(value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else REPO_ROOT / path


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def tex_escape(value: Any) -> str:
    text = str(value)
    return (
        text.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
    )


def write_tex_table(path: Path, columns: list[tuple[str, str]], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    align = "l" * len(columns)
    lines = [
        "% Generated by scripts/write-paper-summary-tables.py; do not edit.",
        f"\\begin{{tabular}}{{{align}}}",
        "\\toprule",
        " & ".join(tex_escape(label) for _, label in columns) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(tex_escape(row.get(key, "")) for key, _ in columns) + " \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def fraction(summary: dict[str, Any], key: str) -> str:
    item = summary.get(key, {})
    return f"{item.get('passed', 0)}/{item.get('total', 0)}"


def manifest_pair(path: Path) -> str:
    tasks = load_yaml(path).get("tasks", [])
    positives = sum(1 for task in tasks if task.get("type") == "positive")
    negatives = sum(1 for task in tasks if task.get("type") == "negative")
    return f"{positives}/{negatives}"


def manifest_summary(path: Path) -> dict[str, Any]:
    tasks = load_yaml(path).get("tasks", [])
    levels = Counter(str(task.get("level")) for task in tasks)
    case_positive = 0
    case_negative = 0
    for task in tasks:
        features = set(task.get("expected_features", []))
        if "calibration" in features:
            continue
        if task.get("type") == "positive" and "case_study" in features:
            case_positive += 1
        if task.get("type") == "negative" and "case_study_negative" in features:
            case_negative += 1
    return {
        "pos_neg": manifest_pair(path),
        "levels": ", ".join(f"{level}={levels[level]}" for level in sorted(levels)),
        "case_pairs": f"{case_positive}/{case_negative}",
    }


def split_rows(args: argparse.Namespace) -> list[dict[str, Any]]:
    specs = [
        ("Public-dev", args.public_manifest, args.public_result, "Yosys reference"),
        ("Held-out", args.heldout_manifest, args.heldout_result, "Yosys reference"),
        ("Realism supplement", args.realism_manifest, args.realism_result, "Yosys reference"),
    ]
    rows = []
    for name, manifest, result, qor_label in specs:
        summary = load_json(repo_path(result)).get("summary", {})
        manifest_stats = manifest_summary(repo_path(manifest))
        sim_modes = summary.get("sim_mode_counts", {})
        formal_modes = summary.get("formal_mode_counts", {})
        qor = summary.get("qor", {})
        sim_declared = sim_modes.get("declared", 0)
        formal_declared = formal_modes.get("declared", 0)
        qor_value = f"{qor.get('available_tasks', 0)}/{qor.get('total', 0)} {qor_label}"
        rows.append(
            {
                "split": name,
                "tasks": summary.get("total_tasks", 0),
                "pos_neg": manifest_stats["pos_neg"],
                "levels": manifest_stats["levels"],
                "case_pairs": manifest_stats["case_pairs"],
                "expected": fraction(summary, "expected_outcome_pass"),
                "sim": f"{fraction(summary, 'sim_pass')} ({sim_declared} declared)",
                "formal": f"{fraction(summary, 'formal_pass')} ({formal_declared} declared)",
                "qor": qor_value,
            }
        )
    return rows


def repair_rows(aggregate: dict[str, Any]) -> list[dict[str, Any]]:
    compact = aggregate.get("llm_compact_summary", [])
    paired = aggregate.get("llm_paired_comparisons", [])

    def positive(split: str, baseline: str) -> str:
        for row in compact:
            if row.get("split") == split and row.get("baseline") == baseline:
                return str(row.get("positive_pass", "n/a"))
        return "n/a"

    plain_public = positive("public-dev", "JSON AST")
    plain_heldout = positive("held-out", "JSON AST")
    plain_realism = positive("realism", "JSON AST")
    repair_public = positive("public-dev", "JSON AST repair")
    repair_heldout = positive("held-out", "JSON AST repair")
    repair_realism = positive("realism", "JSON AST repair")
    public_wins = heldout_wins = realism_wins = 0
    for row in paired:
        if row.get("comparison") != "mico_json_ast_repair_vs_mico_json_ast":
            continue
        split = row_split(row)
        if split == "public-dev":
            public_wins = int(row.get("target_wins", 0))
        elif split == "held-out":
            heldout_wins = int(row.get("target_wins", 0))
        elif split == "realism":
            realism_wins = int(row.get("target_wins", 0))
    return [
        {
            "path": "Plain JSON AST",
            "public": plain_public,
            "heldout": plain_heldout,
            "realism": plain_realism,
            "wins": "baseline",
            "provenance": "model structured JSON",
        },
        {
            "path": "JSON AST + repair",
            "public": repair_public,
            "heldout": repair_heldout,
            "realism": repair_realism,
            "wins": f"{public_wins} public, {heldout_wins} held-out, {realism_wins} realism",
            "provenance": "deterministic_adapter_instance_collapse",
        },
        {
            "path": "Free-form LLM patch",
            "public": "0 recorded wins",
            "heldout": "0 recorded wins",
            "realism": "0 recorded wins",
            "wins": "0",
            "provenance": "not claimed",
        },
    ]


def row_split(row: dict[str, Any]) -> str:
    split = str(row.get("split", ""))
    if split:
        return split
    comparable = row.get("comparable_tasks")
    if comparable in {186, 249}:
        return "public-dev"
    if comparable in {60, 120}:
        return "held-out"
    if comparable == 90:
        return "realism"
    return "unknown"


def failure_rows(aggregate: dict[str, Any]) -> list[dict[str, Any]]:
    class_map = {
        "compiler_pass": "compiler/lint pass",
        "sv_lint_pass": "compiler/lint pass",
        "repair_compiler_pass": "repair compiler pass",
        "model_rejected": "model rejected",
        "response_json_invalid": "invalid JSON",
        "sv_lint_fail": "SV lint fail",
        "unsafe_not_rejected": "unsafe not rejected",
        "compiler_rejected": "compiler rejected",
    }

    def category_class(category: str) -> str:
        if category.startswith("compiler:"):
            return "parser/name error"
        return class_map.get(category, category)

    by_baseline: dict[str, Counter[str]] = defaultdict(Counter)
    for row in aggregate.get("llm_failure_taxonomy", []):
        by_baseline[str(row.get("baseline", ""))][category_class(str(row.get("category", "")))] += int(
            row.get("attempts", 0)
        )

    labels = {
        "direct_verilog": "Direct Verilog",
        "sv_interface": "SV interface",
        "mico_source": "MICO source",
        "mico_json_ast": "JSON AST",
        "mico_json_ast_repair": "JSON AST repair",
    }
    rows = []
    for baseline in ["direct_verilog", "sv_interface", "mico_source", "mico_json_ast", "mico_json_ast_repair"]:
        counts = by_baseline.get(baseline, Counter())
        dominant = ", ".join(f"{name}={count}" for name, count in counts.most_common(3))
        rows.append(
            {
                "baseline": labels[baseline],
                "dominant": dominant,
                "events": sum(counts.values()),
            }
        )
    return rows


def qor_rows(args: argparse.Namespace) -> list[dict[str, Any]]:
    public = load_json(repo_path(args.public_result)).get("summary", {}).get("qor", {})
    heldout = load_json(repo_path(args.heldout_result)).get("summary", {}).get("qor", {})
    realism = load_json(repo_path(args.realism_result)).get("summary", {}).get("qor", {})
    rows = [
        {
            "scope": "Yosys structural/generic public-dev",
            "rows": f"{public.get('available_tasks', 0)}/{public.get('total', 0)}",
            "status": "reference wrappers",
            "claim": "area/wire/mapped-cell parity",
        },
        {
            "scope": "Yosys structural/generic held-out",
            "rows": f"{heldout.get('available_tasks', 0)}/{heldout.get('total', 0)}",
            "status": "reference wrappers",
            "claim": "area/wire/mapped-cell parity",
        },
        {
            "scope": "Yosys structural/generic realism",
            "rows": f"{realism.get('available_tasks', 0)}/{realism.get('total', 0)}",
            "status": "reference wrappers",
            "claim": "area/wire/mapped-cell parity",
        },
    ]
    vivado_path = repo_path(args.vivado_summary)
    if vivado_path.exists():
        vivado = load_json(vivado_path)
        tasks = {record.get("task") for record in vivado.get("records", []) if record.get("kind") == "generated"}
        passed = [
            record
            for record in vivado.get("records", [])
            if record.get("kind") == "generated" and record.get("status") == "pass" and record.get("timing_pass") is True
        ]
        coverage = vivado.get("coverage_summary", {})
        split_rows = coverage.get("total_reference_enabled_rows") if isinstance(coverage, dict) else None
        split_row_text = (
            f"{split_rows}/{split_rows} split rows; {len(passed)}/{len(tasks)} task pairs"
            if isinstance(split_rows, int) and split_rows > 0
            else f"{len(passed)}/{len(tasks)}"
        )
        rows.append(
            {
                "scope": "Vivado OOC subset",
                "rows": split_row_text,
                "status": str(vivado.get("vivado_part", "unknown")),
                "claim": "positive WNS, not routed closure",
            }
        )
    else:
        rows.append(
            {
                "scope": "Vivado OOC subset",
                "rows": "missing",
                "status": "host artifact absent",
                "claim": "not included",
            }
        )
    rows.append(
        {
            "scope": "Routed implementation",
            "rows": "0",
            "status": "not run",
            "claim": "not claimed",
        }
    )
    return rows


def static_check_rows() -> list[dict[str, str]]:
    return [
        {
            "check": "Namespace/reference",
            "diagnostic": "Duplicate*, Unknown*",
            "evidence": "public/held-out negative manifests",
        },
        {
            "check": "Endpoint role/direction",
            "diagnostic": "DirectionMismatch",
            "evidence": "paired unsafe reversals",
        },
        {
            "check": "Interface/protocol",
            "diagnostic": "InterfaceMismatch, ProtocolMismatch",
            "evidence": "missing bridge/packetizer variants",
        },
        {
            "check": "Width/adapters",
            "diagnostic": "WidthMismatch, AdapterMismatch",
            "evidence": "width and MMIO adapter tasks",
        },
        {
            "check": "Clock/reset domain",
            "diagnostic": "ClockDomainMismatch",
            "evidence": "CDC-without-adapter variants",
        },
        {
            "check": "Ready/valid contract subset",
            "diagnostic": "ContractViolation",
            "evidence": "contract negative tasks",
        },
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-manifest", default="benchmarks/module_compose_bench_manifest.yaml")
    parser.add_argument("--heldout-manifest", default="benchmarks/module_compose_bench_heldout.yaml")
    parser.add_argument("--realism-manifest", default="benchmarks/module_compose_bench_realism.yaml")
    parser.add_argument("--public-result", default="build/bench/seed_results.json")
    parser.add_argument("--heldout-result", default="build/bench/heldout_results.json")
    parser.add_argument("--realism-result", default="build/bench/realism_results.json")
    parser.add_argument("--llm-aggregate", default="build/bench/aggregate_llm_v4.json")
    parser.add_argument("--vivado-summary", default="build/reports/vivado-host/vivado_qor_subset_summary.json")
    parser.add_argument("--out-dir", default="build/paper_tables/paper_summary")
    args = parser.parse_args()

    aggregate = load_json(repo_path(args.llm_aggregate))
    out_dir = repo_path(args.out_dir)
    write_tex_table(
        out_dir / "static_checks.tex",
        [("check", "Check"), ("diagnostic", "Diagnostic codes"), ("evidence", "Evidence")],
        static_check_rows(),
    )
    write_tex_table(
        out_dir / "benchmark_split_summary.tex",
        [
            ("split", "Split"),
            ("tasks", "Tasks"),
            ("pos_neg", "Pos/Neg"),
            ("levels", "Levels"),
            ("case_pairs", "Cases/paired negatives"),
            ("expected", "Expected"),
            ("sim", "Simulation"),
            ("formal", "Formal"),
            ("qor", "QoR"),
        ],
        split_rows(args),
    )
    write_tex_table(
        out_dir / "llm_repair_boundary.tex",
        [
            ("path", "Path"),
            ("public", "Public positives"),
            ("heldout", "Held-out positives"),
            ("realism", "Realism positives"),
            ("wins", "Added wins"),
            ("provenance", "Provenance"),
        ],
        repair_rows(aggregate),
    )
    write_tex_table(
        out_dir / "llm_failure_taxonomy_compact.tex",
        [("baseline", "Baseline"), ("dominant", "Dominant events"), ("events", "Events")],
        failure_rows(aggregate),
    )
    write_tex_table(
        out_dir / "qor_scope_summary.tex",
        [("scope", "Scope"), ("rows", "Rows"), ("status", "Status"), ("claim", "Claim")],
        qor_rows(args),
    )
    print(f"wrote paper summary tables to {out_dir.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
